# Generated by Django 5.1.6 on 2025-03-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maestro',
            options={'verbose_name': 'Maestro', 'verbose_name_plural': 'Maestros'},
        ),
    ]
