# Generated by Django 5.1.6 on 2025-04-25 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividadesTangram', '0003_actividad_activo'),
        ('equipos', '0004_remove_equipos_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaTangram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(editable=False, max_length=255)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='actividadesTangram.actividad')),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='equipos.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='evidencias.evidenciatangram')),
            ],
        ),
    ]
