# Generated by Django 5.1.6 on 2025-05-06 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_estudiante_last_login_alter_estudiante_equipo'),
        ('evidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=100)),
                ('nickname_estudiante', models.CharField(max_length=50)),
                ('mensajes_enviados', models.PositiveIntegerField(default=0)),
                ('respuestas_enviadas', models.PositiveIntegerField(default=0)),
                ('piezas_movidas', models.PositiveIntegerField(default=0)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiantes.estudiante')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='evidencias.evidenciatangram')),
            ],
        ),
    ]
