# Generated by Django 5.1.6 on 2025-05-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0002_estadisticaevidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciatangram',
            name='banco_tangram_original',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evidenciatangram',
            name='nombre_equipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
