# Generated by Django 5.1.6 on 2025-05-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0003_evidenciatangram_banco_tangram_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciatangram',
            name='nombre_actividad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='evidenciatangram',
            name='nombre_salon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
