# Generated by Django 5.1.6 on 2025-06-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0004_evidenciatangram_nombre_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciatangram',
            name='horas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidenciatangram',
            name='minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidenciatangram',
            name='segundos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
