# Generated by Django 5.1.6 on 2025-06-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0005_evidenciatangram_horas_evidenciatangram_minutos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciatangram',
            name='horas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evidenciatangram',
            name='minutos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='evidenciatangram',
            name='segundos',
            field=models.PositiveIntegerField(),
        ),
    ]
