# Generated by Django 5.1.6 on 2025-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias', '0006_alter_evidenciatangram_horas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciatangram',
            name='tiempo_asignado_horas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidenciatangram',
            name='tiempo_asignado_minutos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidenciatangram',
            name='tiempo_asignado_segundos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
