# Generated by Django 5.1.6 on 2025-03-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salones', '0002_salon_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('horas', models.PositiveIntegerField()),
                ('minutos', models.PositiveIntegerField()),
                ('segundos', models.PositiveIntegerField()),
                ('banco_tangrams', models.JSONField()),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salones.salon')),
            ],
        ),
    ]
