# Generated by Django 5.1.6 on 2025-04-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividadesTangram', '0002_alter_actividad_options_actividad_maestroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
