# Generated by Django 5.1.6 on 2025-03-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('salones', '0002_salon_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salones.salon'),
        ),
    ]
