# Generated by Django 5.1.6 on 2025-03-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_estudiante_salon'),
        ('salones', '0002_salon_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salones.salon'),
        ),
    ]
