# Generated by Django 5.1.6 on 2025-03-04 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipos_estudiantes_equipos_salon'),
        ('estudiantes', '0003_alter_estudiante_nickname_alter_estudiante_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipos.equipos'),
        ),
    ]
