# Generated by Django 5.1.6 on 2025-03-12 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_remove_equipos_estudiantes'),
        ('estudiantes', '0004_estudiante_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipos.equipos'),
        ),
    ]
