# Generated by Django 5.1.6 on 2025-03-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
