# Generated by Django 5.1.6 on 2025-03-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipos',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
    ]
