# Generated by Django 5.1.6 on 2025-03-04 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_alter_equipos_options'),
        ('estudiantes', '0003_alter_estudiante_nickname_alter_estudiante_salon'),
        ('salones', '0002_salon_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='estudiantes.estudiante'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='salon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salones.salon'),
        ),
    ]
