# Generated by Django 5.1.6 on 2025-03-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_equipos_estudiantes_equipos_salon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='estudiantes',
        ),
    ]
