# Generated by Django 5.1.6 on 2025-03-13 00:45

import django.db.models.deletion
import sesion_juego.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0004_remove_equipos_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=sesion_juego.models.generar_codigo, max_length=10, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipos')),
            ],
        ),
    ]
